
stages:
  - deploy

before_script:
  - export KUBECONFIG=$HOME/.kube/config
  - kubectl config use-context minikube
  - kubectl version
  - helm version

deploy-postgresql:
  stage: deploy
  script:
    - helm repo add cetic https://cetic.github.io/helm-charts
    - helm repo update
    - helm upgrade --install postgresql cetic/postgresql \
        --version 0.2.5 \
        --namespace infra \
        --set configKubernetes.spilo_runasuser=101 \
        --set configKubernetes.spilo_runasgroup=103 \
        --set configKubernetes.spilo_fsgroup=103
    - kubectl apply -f k8s/postgresql/postgresql-cluster.yaml -n infra
  only:
    - main
  tags:
    - main

deploy-kafka:
  stage: deploy
  script:
    - helm repo add kafka https://helm-charts.itboon.top/kafka/
    - helm repo update
    - helm upgrade --install kafka kafka/kafka \
        --version 18.0.1 \
        --namespace infra \
        --set cp-kafka.persistence.size=10Gi \
        --set cp-kafka.replicas=1 \
        --set cp-zookeeper.persistence.size=10Gi \
        --set cp-zookeeper.replicas=1
  only:
    - main
  tags:
    - main

deploy-rabbitmq:
  stage: deploy
  script:
    - helm repo add groundhog2k https://groundhog2k.github.io/helm-charts/
    - helm repo update
    - helm upgrade --install rabbitmq groundhog2k/rabbitmq \
        --version 2.1.1 \
        --namespace infra \
        --set auth.username="$RABBITMQ_USERNAME" \
        --set auth.password="$RABBITMQ_PASSWORD" \
        --set persistence.size=10Gi \
        --set replicaCount=1
  only:
    - main
  tags:
    - main
