image:
  name: bitnami/kubectl:latest
  entrypoint: [""]

stages:
  - deploy

variables:
  KUBECONFIG: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/kubeconfig"
  NAMESPACE: infra

before_script:
  - echo "$KUBE_CONFIG" > ~/.kube/config
  - echo "$KUBE_CONFIG"
  - cat ~/.kube/config
  - chmod 600 ~/.kube/config
  - kubectl version
#   - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
#   - chmod 700 get_helm.sh
#   - ./get_helm.sh

deploy-postgresql:
  stage: deploy
  tags:
    - main
  script:
    - helm repo add cetic https://cetic.github.io/helm-charts
    - helm repo update
    - helm upgrade --install postgresql cetic/postgresql --version 0.2.5 --namespace infra --set configKubernetes.spilo_runasuser=101 --set configKubernetes.spilo_runasgroup=103 --set configKubernetes.spilo_fsgroup=103
    - kubectl apply -f k8s/postgresql/postgresql-cluster.yaml -n infra
  only:
    - main

deploy-kafka:
  stage: deploy
  tags:
    - main
  script:
    - helm repo add kafka https://helm-charts.itboon.top/kafka/
    - helm repo update
    - helm upgrade --install kafka kafka/kafka --version 18.0.1 --namespace infra --set cp-kafka.persistence.size=10Gi --set cp-kafka.replicas=1 --set cp-zookeeper.persistence.size=10Gi --set cp-zookeeper.replicas=1

  only:
    - main

deploy-rabbitmq:
  stage: deploy
  tags:
    - main
  script:
    - helm repo add groundhog2k https://groundhog2k.github.io/helm-charts/
    - helm repo update
    - helm upgrade --install rabbitmq groundhog2k/rabbitmq --version 2.1.1 --namespace infra --set auth.username="$RABBITMQ_USERNAME" --set auth.password="$RABBITMQ_PASSWORD" --set persistence.size=10Gi --set replicaCount=1
  only:
    - main