image:
  name: bitnami/kubectl:latest
  entrypoint: [""]

stages:
  - deploy

variables:
  KUBECONFIG: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/kubeconfig"
  NAMESPACE: infra

before_script:
  - echo "$KUBE_CONFIG" > ~/.kube/config
  - chmod 600 ~/.kube/config
  # Установка Helm (если не предустановлен)
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - ./get_helm.sh

deploy-postgresql:
  stage: deploy
  tags:
    - main
  script:
    - helm repo add crunchy https://charts.crunchydata.com/
    - helm upgrade --install postgresql crunchy/postgresql \
        --namespace infra \
        --set postgresqlPassword=$POSTGRES_PASSWORD \
        --set persistence.size=10Gi \
        --set replicaCount=1
  only:
    - main

deploy-kafka:
  stage: deploy
  tags:
    - main
  script:
    - kubectl create namespace infra || true
    - kubectl apply -f https://strimzi.io/install/latest?namespace=infra
    - kubectl apply -f k8s/kafka/kafka-cluster.yaml -n infra
  only:
    - main

deploy-rabbitmq:
  stage: deploy
  tags:
    - main
  script:
    - helm repo add rabbitmq https://charts.helm.sh/stable
    - helm upgrade --install rabbitmq rabbitmq/rabbitmq \
        --namespace infra \
        --set auth.username=$RABBITMQ_USERNAME \
        --set auth.password=$RABBITMQ_PASSWORD \
        --set persistence.size=10Gi \
        --set replicaCount=1
  only:
    - main